### ISSUE TITLE
I can not open the sln with VS Stud 2015.

### ISSUE THREAD

**Issue by dockergirl** [awslabs/aws-lex-net-chatbot#2]
...\aws-lex-net-chatbot-master\Code\dotnetLexChatBot\dotnetLexChatBot.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  ...\aws-lex-net-chatbot-master\Code\dotnetLexChatBot\dotnetLexChatBot.csproj

**Comment by tawalke** [comment]
Hi @dockergirl Unfortunately this is a issue noted by MS that projects built or migrated to VS 2017 can't be opened with 2015 due to changes in Build process. See reference to this issue here on the dotnet repo: https://github.com/dotnet/project-system/issues/1558 

However, you can download the VS Community version: https://www.visualstudio.com/community/ OR the free VS Code https://code.visualstudio.com/ to open the project. You can have different VS versions side by side.
